services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run celery -A backend.app.services.chat.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    user: "501:20" 

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"