services:
  app:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - ollama
    volumes:
      - .:/app
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Correct hostname

  redis:
    image: "redis:latest"
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  ollama:
    image: "ollama/ollama:latest"  # Ensure you're using the correct Ollama image
    container_name: ollama_service
    restart: always
    ports:
      - "11434:11434"  # Expose API for communication

  celery_worker:
    build: .  
    container_name: celery_worker
    restart: always
    depends_on:
      - app
      - redis
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434  # Ensure Celery uses the correct Ollama API host
      - CELERY_BROKER_URL=redis://redis:6379/0  # Use Redis service name, not localhost
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: poetry run celery -A backend.app.services.chat.celery_app worker --loglevel=info

  celery_beat:
    build: .  
    container_name: celery_beat
    restart: always
    depends_on:
      - celery_worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0  # Ensure Celery Beat also connects correctly
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    command: poetry run celery -A backend.app.services.chat.celery_app beat --loglevel=info